#!/usr/bin/env swift

// Renders the WordLern app icon: assets/icon.svg (source, also used by the website)
// and the 1024×1024 PNG the asset catalogue wants.
//
//   swift tools/make_icon.swift            # writes both, plus 60×60 and 120×120 proofs
//   swift tools/make_icon.swift --png 60   # one extra size, for checking small rendering
//
// The ß is taken from the system font and written out as an outline, so neither the SVG
// nor the PNG depends on a font being installed wherever it is opened.

import AppKit
import CoreText
import Foundation

// MARK: - Design

let canvas: CGFloat = 1024

let background = "#15181D"   // near-black, the app's darkest surface
let glyphColour = "#F7F5F0"  // off-white
let barBlack = "#3C434D"     // the flag's black band, lifted so it reads on the background
let barRed = "#D8232A"
let barGold = "#F0C419"

// The glyph is measured by its own bounding box and placed by hand, so the icon is
// balanced optically rather than by font metrics (which include ascender space the ß
// does not use).
let glyphHeight: CGFloat = 560   // bounding-box height of the ß
let glyphCentreY: CGFloat = 450  // from the top of the canvas

let barWidth: CGFloat = 430
let barHeight: CGFloat = 46
let barTop: CGFloat = 806

// MARK: - The ß outline

/// The ß of the system font at `glyphHeight`, centred on `glyphCentreY`, in a
/// y-down coordinate space with the origin at the top left of the canvas.
func glyphPath() -> CGPath {
    let font = NSFont.systemFont(ofSize: 1000, weight: .semibold) as CTFont
    var character: UniChar = 0x00DF  // ß
    var glyph = CGGlyph()
    guard CTFontGetGlyphsForCharacters(font, &character, &glyph, 1),
          let raw = CTFontCreatePathForGlyph(font, glyph, nil) else {
        fatalError("the system font has no ß")
    }

    // CoreText hands back a y-up path sized to the 1000pt em. Scale it to the
    // wanted height, flip it, and centre it on its own ink.
    let ink = raw.boundingBoxOfPath
    let scale = glyphHeight / ink.height
    var transform = CGAffineTransform.identity
        .translatedBy(x: canvas / 2, y: glyphCentreY)
        .scaledBy(x: scale, y: -scale)
        .translatedBy(x: -ink.midX, y: -ink.midY)
    return raw.copy(using: &transform)!
}

// MARK: - SVG

func svgPathData(_ path: CGPath) -> String {
    func f(_ value: CGFloat) -> String {
        String(format: "%.2f", value)
    }
    var parts: [String] = []
    path.applyWithBlock { element in
        let points = element.pointee.points
        switch element.pointee.type {
        case .moveToPoint:
            parts.append("M\(f(points[0].x)) \(f(points[0].y))")
        case .addLineToPoint:
            parts.append("L\(f(points[0].x)) \(f(points[0].y))")
        case .addQuadCurveToPoint:
            parts.append("Q\(f(points[0].x)) \(f(points[0].y)) \(f(points[1].x)) \(f(points[1].y))")
        case .addCurveToPoint:
            parts.append("C\(f(points[0].x)) \(f(points[0].y)) \(f(points[1].x)) \(f(points[1].y)) \(f(points[2].x)) \(f(points[2].y))")
        case .closeSubpath:
            parts.append("Z")
        @unknown default:
            break
        }
    }
    return parts.joined(separator: " ")
}

func svg(_ path: CGPath) -> String {
    let radius = barHeight / 2
    let third = barWidth / 3
    let left = (canvas - barWidth) / 2

    // One continuous bar in three colours. Separate segments with gaps would close up
    // into mush at 60×60, so the colours meet edge to edge like the flag's bands.
    func segment(_ colour: String, index: Int) -> String {
        """
            <rect x="\(left + third * CGFloat(index))" y="\(barTop)" width="\(third)" height="\(barHeight)" fill="\(colour)"/>
        """
    }

    return """
    <svg xmlns="http://www.w3.org/2000/svg" width="1024" height="1024" viewBox="0 0 1024 1024">
      <title>WordLern</title>
      <!-- Generated by tools/make_icon.swift — edit the script, not this file. -->
      <defs>
        <clipPath id="bar">
          <rect x="\(left)" y="\(barTop)" width="\(barWidth)" height="\(barHeight)" rx="\(radius)"/>
        </clipPath>
      </defs>
      <rect width="1024" height="1024" fill="\(background)"/>
      <path d="\(svgPathData(path))" fill="\(glyphColour)"/>
      <g clip-path="url(#bar)">
    \(segment(barBlack, index: 0))
    \(segment(barRed, index: 1))
    \(segment(barGold, index: 2))
      </g>
    </svg>
    """
}

// MARK: - PNG

func colour(_ hex: String) -> CGColor {
    var value: UInt64 = 0
    Scanner(string: String(hex.dropFirst())).scanHexInt64(&value)
    return CGColor(red: CGFloat((value >> 16) & 0xFF) / 255,
                   green: CGFloat((value >> 8) & 0xFF) / 255,
                   blue: CGFloat(value & 0xFF) / 255,
                   alpha: 1)
}

/// Opaque, no alpha channel, no rounded corners — iOS masks the squircle itself.
func png(_ path: CGPath, size: CGFloat) -> Data {
    let space = CGColorSpace(name: CGColorSpace.sRGB)!
    guard let context = CGContext(data: nil,
                                  width: Int(size),
                                  height: Int(size),
                                  bitsPerComponent: 8,
                                  bytesPerRow: 0,
                                  space: space,
                                  bitmapInfo: CGImageAlphaInfo.noneSkipLast.rawValue) else {
        fatalError("could not make a \(Int(size))×\(Int(size)) context")
    }

    // Flip into the same y-down space the SVG uses, so one set of coordinates serves both.
    context.translateBy(x: 0, y: size)
    let scale = size / canvas
    context.scaleBy(x: scale, y: -scale)

    context.setFillColor(colour(background))
    context.fill(CGRect(x: 0, y: 0, width: canvas, height: canvas))

    context.setFillColor(colour(glyphColour))
    context.addPath(path)
    context.fillPath()

    let left = (canvas - barWidth) / 2
    let third = barWidth / 3
    context.saveGState()
    context.addPath(CGPath(roundedRect: CGRect(x: left, y: barTop, width: barWidth, height: barHeight),
                           cornerWidth: barHeight / 2,
                           cornerHeight: barHeight / 2,
                           transform: nil))
    context.clip()
    for (index, hex) in [barBlack, barRed, barGold].enumerated() {
        context.setFillColor(colour(hex))
        context.fill(CGRect(x: left + third * CGFloat(index), y: barTop, width: third, height: barHeight))
    }
    context.restoreGState()

    guard let image = context.makeImage() else { fatalError("no image") }
    let bitmap = NSBitmapImageRep(cgImage: image)
    guard let data = bitmap.representation(using: .png, properties: [:]) else { fatalError("no png") }
    return data
}

// MARK: - Run

let root = URL(fileURLWithPath: FileManager.default.currentDirectoryPath)

let path = glyphPath()

var sizes: [CGFloat] = [1024, 120, 60]
if let index = CommandLine.arguments.firstIndex(of: "--png"),
   let extra = CommandLine.arguments.dropFirst(index + 1).first.flatMap(Double.init) {
    sizes = [CGFloat(extra)]
}

if sizes.contains(1024) {
    let svgURL = root.appendingPathComponent("assets/icon.svg")
    try! FileManager.default.createDirectory(at: svgURL.deletingLastPathComponent(),
                                             withIntermediateDirectories: true)
    try! svg(path).write(to: svgURL, atomically: true, encoding: .utf8)
    print("wrote assets/icon.svg")

    let iconURL = root.appendingPathComponent("thousand/Assets.xcassets/AppIcon.appiconset/icon-1024.png")
    try! png(path, size: 1024).write(to: iconURL)
    print("wrote thousand/Assets.xcassets/AppIcon.appiconset/icon-1024.png")
}

for size in sizes where size != 1024 {
    let url = root.appendingPathComponent("build/icon-proof-\(Int(size)).png")
    try! FileManager.default.createDirectory(at: url.deletingLastPathComponent(),
                                             withIntermediateDirectories: true)
    try! png(path, size: size).write(to: url)
    print("wrote build/icon-proof-\(Int(size)).png")
}
